"""Core engine — scanner, identifier, hasher, organizer, exporter."""

from romulus.core.dat_parser import (
    DatEntry,
    load_all_dats,
    match_hashes,
    parse_dat_file,
    parse_region_from_name,
)
from romulus.core.exporter import (
    BUILTIN_PROFILES_DIR,
    ExportFilters,
    ExportOptions,
    ExportPreview,
    ExportSummary,
    copy_artwork,
    export_collection,
    generate_gamelist_xml,
    generate_m3u_playlists,
    load_all_profiles,
    load_profile,
    preview_export,
)
from romulus.core.hasher import (
    HashResult,
    hash_library,
    hash_rom,
    normalize_rom_content,
)
from romulus.core.identifier import extract_header_title
from romulus.core.organizer import (
    ACTION_COLLISION,
    ACTION_DELETE_DUPLICATE,
    ACTION_MERGE_FOLDER,
    ACTION_RENAME,
    OrganizeAction,
    OrganizePlan,
    OrganizeSummary,
    analyze_library,
    detect_collisions,
    execute_plan,
    find_alias_merges,
    find_cross_extension_dupes,
    find_duplicates,
    find_renameable_roms,
)
from romulus.core.scanner import (
    SIDE_FILE_EXTENSIONS,
    ParsedFilename,
    ScanResult,
    detect_system,
    generate_fuzzy_key,
    group_into_games,
    is_rom_file,
    is_side_file,
    parse_filename,
    scan_library,
)

__all__ = [
    "ACTION_COLLISION",
    "ACTION_DELETE_DUPLICATE",
    "ACTION_MERGE_FOLDER",
    "ACTION_RENAME",
    "BUILTIN_PROFILES_DIR",
    "SIDE_FILE_EXTENSIONS",
    "DatEntry",
    "ExportFilters",
    "ExportOptions",
    "ExportPreview",
    "ExportSummary",
    "HashResult",
    "OrganizeAction",
    "OrganizePlan",
    "OrganizeSummary",
    "ParsedFilename",
    "ScanResult",
    "analyze_library",
    "copy_artwork",
    "detect_collisions",
    "detect_system",
    "execute_plan",
    "export_collection",
    "extract_header_title",
    "find_alias_merges",
    "find_cross_extension_dupes",
    "find_duplicates",
    "find_renameable_roms",
    "generate_fuzzy_key",
    "generate_gamelist_xml",
    "generate_m3u_playlists",
    "group_into_games",
    "hash_library",
    "hash_rom",
    "is_rom_file",
    "is_side_file",
    "load_all_dats",
    "load_all_profiles",
    "load_profile",
    "match_hashes",
    "normalize_rom_content",
    "parse_dat_file",
    "parse_filename",
    "parse_region_from_name",
    "preview_export",
    "scan_library",
]
